title: Sensorimotor AI Journal Club
description: Monthly journal club and RL Debate Series
url: https://sensorimotorai.github.io
theme: null
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

minimal_mistakes_skin: default

nav:
  - title: Home
    url: /
  - title: Schedule
    url: /schedule/
  - title: Tags
    url: /tags/
  - title: RL Debates
    url: /debates/

slack_url: https://join.slack.com/t/sensorimotorai/shared_invite/zt-39l98agsh-Y9U1nsk~DTw7WiPBsZtdAA
youtube_url: https://www.youtube.com/@SensorimotorAI

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: timeline
  - scope:
      path: ""
      type: pages
    values:
      sidebar:
        nav: timeline

